### ISSUE TITLE
matlab command 'userpath' returns 0x0 char array 

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/matlab-azure-devops-extension#25]
https://dev.azure.com/iat-ci/ci-test-repo/_build/results?buildId=1748&view=logs&j=43d32c17-ff19-5d0a-58b3-52a09bf40d57&t=cc4ccfe7-cdbc-5a16-bec2-6714bdb53b8e

**Comment by mcafaro** [comment]
Per the [`userpath`](https://www.mathworks.com/help/matlab/ref/userpath.html#d120e1343334) doc:

> The default userpath folder is platform-specific.
> [...]
> - Linux® platforms — $home/Documents/MATLAB if $home/Documents exists.

So `userpath` will only return `$home/Documents/MATLAB` **IF** `$home/Documents` exists. `$home/Documents` does not exist on Microsoft-hosted agents, so `userpath` returns a 0x0 char array. This is the expected behavior of `userpath`.
